### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jwillmer** [Biekos/sentry-mattermost#4]
It's not working for me and I think this plugin has an issue. When I click the test button all works fine but system created exceptions or exceptions created by [sentry cli](https://github.com/getsentry/sentry-cli) do not get fired. 
I suspect that the JSON has changed and this app can't parse the exceptions.

**Comment by jwillmer** [comment]
If I compare this plugin with the Slack plugin (which does that same but for Slack) I see that the notification method is called differently. Maybe this has changed?

Slack notify: https://github.com/getsentry/sentry-slack/blob/a010a0810b7e6904e0748cb4a473cdee39d942e2/src/sentry_slack/plugin.py#L136

Mattermost notify: https://github.com/Biekos/sentry-mattermost/blob/b0c8ae9bf562f405ff0865424d96c4273d03ef45/sentry_mattermost/plugin.py#L143

**Comment by PXke** [comment]
Dear @jwillmer, 

Thank you for creating that issue. 

Yes, I have changed the way we called the notify function because it seems to be the favorite way to do it:

https://github.com/getsentry/sentry/blob/1d3313bea9464d0770934a426f39cb404e8a64f4/src/sentry/plugins/bases/notify.py#L62

The `NotificationPlugin`,  has a `notify` function that is then calling `notify_users`. One of the bug of the plugin was that the `notify` function parameters changed, so to avoid that kind of problem in the future, I used the prefered `notify_users` function. 

The problem you describe me look like if the plugin is not installed in the `worker` container but only in the `web` one. Indeed when you test the plugin through the interface, it is using the `web` container to test the plugin. 

For real events, it is going through the `worker` one, and therefore, if the plugin is not installed there it will not trigger it. 

Tell me if it helps. You can contact me directly through skype @Laton5. 

Have a wonderful day
My best regards.

**Comment by jwillmer** [comment]
I'm using [sentry/onpremise](https://github.com/getsentry/onpremise) to build my images and added the sentry-mattermost plugin in the `requirements.txt`. That is working since after I build the image I can configure the plugin. The `worker` as well as the `web` docker container is using the same image. So this should not be the problem. Does the plugin work for you if you issue an event via the `sentry-cli`?

```
export SENTRY_DSN='https://examplePublicKey@o0.ingest.sentry.io/0'
sentry-cli send-event -m "Hello from Sentry"
```

Requirements.txt:
```
# Add plugins here
git+git://github.com/Biekos/sentry-mattermost.git@master#egg=sentry-mattermost
```

**Comment by jwillmer** [comment]
Were is a new feature called Alerts. You need to manually enable alerts for legacy integrations to get it to work.

![image](https://user-images.githubusercontent.com/1503577/99949798-e4ee9380-2d7b-11eb-9f9d-fefbcd40950d.png)
